# Generated by Django 4.0.6 on 2022-07-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
